/**
 * Sakavi — GitHub Coding Agent client
 *
 * Tokens NEVER live here. All GitHub calls go through the
 * `github-agent` Supabase Edge Function (GITHUB_TOKEN secret).
 *
 * Workflow (enforced server-side):
 *   task → inspect repo → new branch → edit → tests → commit → push → PR
 *   Never direct write to main/master.
 */
(function () {
  const FN = 'github-agent';

  function cfg() {
    return window.SAKAVI_CONFIG || {};
  }

  async function call(action, params) {
    const c = cfg();
    const client = window.sakaviSupabase;
    const url = `${c.supabaseUrl}/functions/v1/${c.githubAgentFunction || FN}`;
    let token = c.supabaseAnonKey;
    if (client) {
      try {
        const { data } = await client.auth.getSession();
        if (data?.session?.access_token) token = data.session.access_token;
      } catch (_) {}
    }

    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
        apikey: c.supabaseAnonKey,
      },
      body: JSON.stringify({ action, repo: c.githubRepo || undefined, ...params }),
    });

    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      throw new Error(data.error || data.message || 'GitHub agent error ' + res.status);
    }
    if (data.error) throw new Error(data.error);
    return data;
  }

  /** Build PR body with summary + test results */
  function buildPrBody({ task, summary, filesChanged, testResults, notes }) {
    const lines = [
      '## Summary',
      summary || task || 'Agent-proposed changes',
      '',
      '## Files changed',
      ...(filesChanged || []).map((f) => `- \`${f}\``),
      '',
      '## Testing',
      testResults || '_Tests not run in this environment — please verify CI._',
      '',
      '## Notes',
      notes || 'Generated by Sakavi GitHub Agent. Review carefully before merge.',
      '',
      '---',
      '- Branch-first workflow (no direct commits to default branch)',
      '- Secrets / `.env` paths blocked by agent policy',
      '- Merge only via Pull Request after human review',
    ];
    return lines.join('\n');
  }

  /**
   * High-level: start a coding task session on a fresh branch.
   */
  async function startTask(task) {
    return call('start_task', { task });
  }

  async function status() {
    return call('status', {});
  }

  async function listFiles(ref) {
    return call('list_tree', { ref });
  }

  async function readFile(path, ref) {
    return call('read_file', { path, ref });
  }

  async function searchCode(query) {
    return call('search_code', { query });
  }

  async function listBranches() {
    return call('list_branches', {});
  }

  async function createBranch(task, base) {
    return call('create_branch', { task, base });
  }

  async function writeFile({ path, content, branch, message, sha }) {
    return call('upsert_file', { path, content, branch, message, sha });
  }

  async function deleteFile({ path, branch, message, sha, confirmDestroy }) {
    return call('delete_file', { path, branch, message, sha, confirmDestroy: !!confirmDestroy });
  }

  async function createPullRequest({ title, body, head, base, draft }) {
    return call('create_pr', { title, body, head, base, draft });
  }

  /**
   * Orchestrated change set:
   * - ensures branch
   * - writes multiple files
   * - opens PR with summary
   * Does NOT auto-merge.
   */
  async function proposeChanges({
    task,
    files, // [{ path, content, message? }]
    summary,
    testResults,
    base,
    draft,
  }) {
    if (!task) throw new Error('task required');
    if (!files || !files.length) throw new Error('files required');

    const session = await startTask(task);
    const branch = session.branch;
    const changed = [];

    for (const f of files) {
      if (!f.path || f.content == null) continue;
      const result = await writeFile({
        path: f.path,
        content: f.content,
        branch,
        message: f.message || `sakavi: update ${f.path}`,
        sha: f.sha,
      });
      changed.push(f.path);
      void result;
    }

    const title = `sakavi: ${task}`.slice(0, 72);
    const body = buildPrBody({
      task,
      summary: summary || task,
      filesChanged: changed,
      testResults: testResults || 'See CI / run tests locally before merge.',
    });

    const pr = await createPullRequest({
      title,
      body,
      head: branch,
      base: base || session.base,
      draft: draft !== false, // default draft for safety
    });

    return {
      ok: true,
      branch,
      files: changed,
      pr,
      policy: session.policy,
    };
  }

  window.SakaviGitHub = {
    call,
    status,
    startTask,
    listFiles,
    readFile,
    searchCode,
    listBranches,
    createBranch,
    writeFile,
    deleteFile,
    createPullRequest,
    proposeChanges,
    buildPrBody,
  };
})();
